---
folders:
  # Folder in which torrent files are download
  # Example downloding my_movie.torrent in src_folder
  src: "c:\should_exists"
  # Folder in which the actual files will be downloaded
  # Example downloading my_move from ftp
  dest: "c:\should_exists"

qbittorrent:
  scheme: https
  domain: "my_domain.com"
  user: "userA"
  password: "Apasswd"
  port: 10412
  clean_older_than: 7

ftp:
  domain: "my_domain.com"
  port: 21
  user: "userA"
  password: "Apasswd"
  tls: True,
  remote_path: "/torrents/qbittorrent/"
#sftp:
#  domain: "my_domain.com"
#  port: 22
#  user: "userA"
#  password: "Apasswd"
#  remote_path: "torrents/qbittorrent/"

toaster:
  duration: 5 # seconds
  title: "qbit-watcher"
